name: app
description: "A  Flutter project."

publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  dio: ^5.7.0
  get_it: ^8.0.2
  lottie: ^3.1.3
  rename: ^3.0.2
  quick_log: ^5.5.0
  flutter_svg: ^2.0.16
#  easy_url_launcher: ^0.0.7
  flutter_screenutil: ^5.9.3
  flutter_launcher_icons: ^0.14.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  assets:
    - assets/svg/
    - assets/fonts/
    - assets/images/
    - assets/lottie/
    - assets/images/lunch/
    - assets/images/soups/
    - assets/images/salads/
    - assets/images/sauces/
    - assets/images/drinks/
    - assets/images/desserts/
    - assets/images/late_night/


  uses-material-design: true

  fonts:
    - family: font
      fonts:
        - asset: assets/fonts/Tajawal.ttf

    - family: title_font
      fonts:
        - asset: assets/fonts/Cairo.ttf

    - family: font2
      fonts:
        - asset: assets/fonts/Audiowide-Regular.ttf